### ISSUE TITLE
Destroying methods request

### ISSUE THREAD

**Issue by thucxuong** [Sam152/Javascript-Equal-Height-Responsive-Rows#17]
Hi Sam,
What your script does is really amazing, and dead simple but super effective.
The only thing missing here is destroy methods.
My problem is to equalize columns within ajax view. Everytime i replace the content, the memory will be leaked and i have no way to destroy or unbind the event.
Thanks in advanced

**Comment by Sam152** [comment]
Okay, seems like a reasonable request and within scope of the plugin. Will look at namespacing some of the events and providing a destroy method.

**Comment by thucxuong** [comment]
Hey Sam, i got something added to your idea.
Why don't we just put a random id data attribute for elements that we gonna bind on, and then using that id number within the event namespace. 
So you can remove completely everything based on that random ID.
Perhaps MD5( random()*1000000 ) haha.

**Comment by Sam152** [comment]
Destroy method has been added. Didn't look like there was a jquery provided unique ID for an element, so used an incremented counter and stored it on the element.
