### ISSUE TITLE
Need to create a 1.0.0 tag

### ISSUE THREAD

**Issue by JakeStoeffler** [Sam152/Javascript-Equal-Height-Responsive-Rows#21]
I had to use `bower install javascript-equal-height-responsive-rows#latest` otherwise Bower failed with the error `ENORESTARGET No tag found that was able to satisfy ~1.0.0`.  I think all you need to do is create a tag called 1.0.0 and then people can simply use `bower install javascript-equal-height-responsive-rows`.

**Comment by Sam152** [comment]
I have pushed that tag. I don't really use bower, so can you let me know if it starts working?

**Comment by JakeStoeffler** [comment]
I think that worked.  Thanks!
